<html>
  <head>
    <link rel=stylesheet type=text/css href="styles.css"/>
    <meta property="og:title" content="GiggleMe" />
    <meta property="og:site_name" content="thegigler.com" />
    <meta property="og:url" content="https://www.thegigler.com/GiggleMe" />
    <meta property="og:image" content="https://www.thegigler.com/GiggleMe/images/giggleme-thumb.jpg" />
    <meta property="og:image:width" content="438" />
    <meta property="og:image:height" content="404" />
    <link rel="shortcut icon" href="images/giggleme.ico"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="giggleme.js"></script>
    <title>GiggleMe</title>
  </head>
  <body>
    <div class="hero-image">
      <div class="hero-text">
      </div>
    </div>

